chore: update deps and switch to yarn
myparcelnl/delivery-options pull request #100
Opened 2022-01-10 14:39 UTC by EdieLemoine

2022-01-13 09:40 UTC, EdieLemoine commented on tests/unit/delivery-options/components/DeliveryOptions.spec.js
> -    expect(app.findChoice('delivery', 'deliver').element).toBeVisible();
Dit patroon werkte niet meer en sloopte de tests. Zie https://github.com/testing-library/jest-dom/issues/338

2022-01-13 09:40 UTC, EdieLemoine commented on src/assets/scss/delivery-options/_map.scss
> +@use "sass:math";
Dit is omdat ik `node-sass` heb geyeet voor `sass` (`dart-sass` dus)

2022-01-13 09:40 UTC, EdieLemoine commented on private/sandboxConfig.js
> -  plugins: [
alle favicons zijn er nu statisch bij gezet, deze hele dependency kan dan lekker weg

2022-01-13 09:40 UTC, EdieLemoine commented on jest.config.js
> +  preset: '@vue/cli-plugin-unit-jest',
al die verwijderde shizzle komt uit deze preset of is niet (meer) nodig

2022-01-13 12:14 UTC, mknijnenberg requested changes

2022-01-13 13:14 UTC, mknijnenberg approved these changes

2022-01-18 15:48 UTC, jonathanheijmans approved these changes

2022-01-19 08:38 UTC, merged