feat: add same day delivery
myparcelnl/delivery-options pull request #101
Opened 2022-01-13 13:10 UTC by EdieLemoine

2022-01-19 09:17 UTC, mknijnenberg approved these changes

2022-01-19 09:30 UTC, Cysword approved these changes

2022-01-19 13:47 UTC, jonathanheijmans requested changes

2022-01-19 13:47 UTC, jonathanheijmans commented on src/delivery-options/config/isPastCutoff.js
> +  return hourHasPassed && (hourIsSame ? minutesHavePassed : true);
Die ternary in de return vind ik persoonlijk viezer dan een mixed && en ||

Alternatieve sugestie voor dit block:

```suggestion
  time  = time.padStart(5,0);
  const date = new Date();
  currentTime = `${date.getHours()}`.padStart(2, 0) + ':' + `${date.getHours()}`.padStart(2, 0);
  return time < currentTime`
```

2022-01-19 13:47 UTC, jonathanheijmans commented on src/delivery-options/data/delivery/dependencies/possibilityIsSameDay.js
> +    return shipmentOption.name === 'same_day_delivery'
Is er geen constante voor "same_day_delivery" ?

2022-01-19 13:55 UTC, markernst97 approved these changes

2022-01-20 09:58 UTC, jonathanheijmans commented on src/delivery-options/config/isPastCutoff.js
> +  return hourHasPassed && (hourIsSame ? minutesHavePassed : true);
prima, vermoed dat ik de het > had moeten zijn op het einde, maar met deze oplossing ben ik ook happy.

2022-01-20 10:05 UTC, jonathanheijmans commented on src/delivery-options/config/isPastCutoff.js
> +  return hourHasPassed && (hourIsSame ? minutesHavePassed : true);
Bij nader inzien moest de tweede getHours een getMinutes zijn

2022-01-20 10:06 UTC, mknijnenberg approved these changes

2022-01-20 10:09 UTC, jonathanheijmans requested changes

2022-01-20 10:09 UTC, jonathanheijmans commented on src/delivery-options/data/delivery/dependencies/possibilityIsSameDay.js
> +    return shipmentOption.name === 'same_day_delivery'
Graag hoor ik waarom dit geen constante is.

2022-01-20 10:14 UTC, jonathanheijmans approved these changes

2022-01-20 10:14 UTC, jonathanheijmans commented on src/delivery-options/config/isPastCutoff.js
> +export function isPastCutoff(time) {
nice

2022-02-04 08:33 UTC, merged