refactor!: rename rjp to instabox
myparcelnl/delivery-options pull request #104
Opened 2022-01-24 08:34 UTC by EdieLemoine

2022-01-24 13:17 UTC, markernst97 approved these changes

2022-01-26 09:38 UTC, jonathanheijmans requested changes
Verder vroeg ik me af in hoeverre er problemen kunnen onstaan mbt backwards compatibility issues

2022-01-26 09:38 UTC, jonathanheijmans commented on tests/unit/delivery-options/deliveryMoment.spec.js
> +    ${MYPARCEL}     | ${INSTABOX} | ${SATURDAY}  | ${false}
Indenting is niet ok hierzo

2022-01-26 09:39 UTC, mknijnenberg approved these changes

2022-01-26 09:39 UTC, jonathanheijmans approved these changes

2022-01-26 09:41 UTC, EdieLemoine commented
@jonathanheijmans daarom is het ook een breaking change ("!"), er wordt vandaag nog een volledige regressie op gedaan

2022-01-26 13:49 UTC, merged