fix: only include delivery date when needed
myparcelnl/delivery-options pull request #108
Opened 2022-02-23 16:14 UTC by markernst97

2022-02-24 15:19 UTC, EdieLemoine requested changes

2022-02-24 15:19 UTC, EdieLemoine commented on src/delivery-options/DeliveryOptions.vue
> +      const isDomesticShipment = this.configBus.address.cc === (NL || BE);
Dit werkt niet, dit wordt altijd NL. Wat je bedoelt is `[NL, BE].includes(cc)`, maar dan nog is dat niet wat "domestic" bij ons betekent.

2022-02-24 15:19 UTC, EdieLemoine commented on src/delivery-options/DeliveryOptions.vue
> +      const isPickup = exportValues.deliveryType === 'pickup';
er is een constante voor `'pickup'`

2022-02-24 15:19 UTC, EdieLemoine commented on src/delivery-options/DeliveryOptions.vue
> +const DATE = 'date';
deze lijkt niet gebruikt te worden

2022-02-24 15:19 UTC, EdieLemoine commented on src/delivery-options/DeliveryOptions.vue
> +        exportValues.deliveryDate = null;
Dit moet in de ExportValues class(es)

2022-03-01 15:18 UTC, EdieLemoine requested changes

2022-03-01 15:18 UTC, EdieLemoine commented on src/delivery-options/config/exports/DeliveryExportValues.js
> +    const showDeliveryDateFromConfig = carrierSettings ? carrierSettings[FEATURE_SHOW_DELIVERY_DATE] : false;
```suggestion
    const showDeliveryDateFromConfig = carrierSettings?[FEATURE_SHOW_DELIVERY_DATE] ?? false;
```

2022-03-01 15:18 UTC, EdieLemoine commented on src/delivery-options/config/exports/DeliveryExportValues.js
> +    const carrierSettings = configBus.get(CARRIER_SETTINGS)[this.carrier];
```suggestion
    const carrierSettings = configBus.get(CARRIER_SETTINGS)?[this.carrier];
```

2022-03-01 15:18 UTC, EdieLemoine commented on src/delivery-options/config/exports/DeliveryExportValues.js
> +import { CARRIER_SETTINGS, FEATURE_SHOW_DELIVERY_DATE } from '../../../data/keys/configKeys';
```suggestion
import { CARRIER_SETTINGS, FEATURE_SHOW_DELIVERY_DATE } from '@/data/keys/configKeys';
```

2022-03-01 15:18 UTC, EdieLemoine commented on src/delivery-options/config/exports/DeliveryExportValues.js
> +    const isNlOrBeShipment = [BE, NL].includes(configBus.address.cc);
gebruik `countryCodes.BELGIUM` en `countryCodes.NETHERLANDS`

2022-03-04 09:23 UTC, joerivanveen approved these changes

2022-03-08 15:26 UTC, joerivanveen approved these changes

2022-03-10 08:49 UTC, joerivanveen approved these changes

2022-03-14 16:12 UTC, EdieLemoine approved these changes

2022-03-14 16:12 UTC, EdieLemoine commented
je tests falen

2022-03-17 10:49 UTC, merged