feat: MY-34068: Add DHL For You
myparcelnl/delivery-options pull request #122
Opened 2022-10-11 10:20 UTC by alexmaat

2022-10-11 11:37 UTC, wthijmen approved these changes

2022-10-12 07:07 UTC, mknijnenberg approved these changes

2022-10-18 07:44 UTC, EdieLemoine requested changes
- dhl same day werkt niet
- andere nieuwe vervoerders mogen er ook bij

2022-10-25 11:40 UTC, EdieLemoine approved these changes

2022-10-25 11:51 UTC, Mark-Ernst approved these changes

2022-10-25 11:52 UTC, joerivanveen approved these changes

2022-10-25 11:53 UTC, wthijmen approved these changes

2022-10-26 07:20 UTC, mknijnenberg approved these changes

2022-10-26 07:22 UTC, merged