feat: allow package small for nl and be
myparcelnl/delivery-options pull request #208
Opened 2024-03-06 14:16 UTC by Mark-Ernst

INT-388

2024-03-06 14:54 UTC, Cysword requested changes

2024-03-06 14:54 UTC, Cysword commented on tests/unit/delivery-options/carrierConfiguration.spec.js
> +  FEATURES_SATURDAY_DELIVERY, FEATURES_PACKAGE_TYPE_PACKAGE_SMALL,
```suggestion
  FEATURES_SATURDAY_DELIVERY,
  FEATURES_PACKAGE_TYPE_PACKAGE_SMALL,
```

2024-03-08 08:20 UTC, joerivanveen approved these changes

2024-03-08 08:49 UTC, Cysword approved these changes

2024-03-08 08:51 UTC, merged