Feat/fix map not reloading with pickup points on address change
myparcelnl/delivery-options pull request #223
Opened 2024-05-01 13:44 UTC by FreekVR

Works around an issue where the pickup locations would never refresh due to memoization not having any arguments to build a cache key from when loading available pickup locations.

Fixes INT-464

2024-05-01 13:49 UTC, EdieLemoine requested changes
je titel is niet goed

2024-05-01 13:49 UTC, EdieLemoine commented on apps/delivery-options/src/composables/useResolvedPickupLocations.ts
> +  () => {
zou je deze naar een variabele kunnen verplaatsen? dat voorkomt deze (lelijke) indenting en zorgt er waarschijnlijk ook voor dat de git diff de changes beter laat zien

2024-05-01 13:58 UTC, EdieLemoine approved these changes
bedoelde de cb, maar dit werkt ook 😛

2024-05-01 14:51 UTC, FreekVR commented
Gaat toch iets mis in de sandbox waar ik met handmatige invoer niet tegenaan liep, lijkt een race condition achtig probleem, ima check :(

2024-05-14 07:35 UTC, joerivanveen approved these changes

2024-05-17 08:33 UTC, joerivanveen approved these changes

2024-05-23 13:18 UTC, merged