feat(): display custom delivery titles in checkout
myparcelnl/delivery-options pull request #255
Opened 2024-10-17 10:19 UTC by MPClerise

INT-575

2024-10-17 13:48 UTC, EdieLemoine requested changes
This is a bug (according to the jira ticket). Also, if you don't have a scope you must omit the parentheses from the title.

Code looks fine, so you just need to update the title :)

2024-10-17 14:00 UTC, GravendeelJochem requested changes

2024-10-17 14:02 UTC, RichardPerdaan commented on apps/delivery-options/src/views/MyParcelDeliveryOptions/DeliveryOptionsForm/DeliveryOptionsForm.vue
> +          label: HEADER_DELIVERY_OPTIONS,
@GravendeelJochem Fallback will have to be created in the PDK or the plugin, so that the DO package will remain small

2024-10-21 09:09 UTC, GravendeelJochem approved these changes

2024-10-23 10:58 UTC, EdieLemoine approved these changes

2024-10-23 11:03 UTC, closed without merging