build: replace fortawesome with vue-fa to reduce bundle size
myparcelnl/delivery-options pull request #53
Opened 2021-02-03 14:37 UTC by EdieLemoine

Differences tested on branch `add-lib-build`.

With [@fortawesome/fontawesome-svg-core](https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core):
```shell
  File                          Size              Gzipped

  dist/myparcel.js              276.62 KiB        90.77 KiB
  dist/myparcel.lib.js          212.30 KiB        67.72 KiB
```

With [vue-fa](https://www.npmjs.com/package/vue-fa):
```shell
  File                          Size              Gzipped

  dist/myparcel.js              244.42 KiB        80.46 KiB
  dist/myparcel.lib.js          180.10 KiB        57.43 KiB
```

2021-02-03 15:59 UTC, jonathanheijmans requested changes

2021-02-03 15:59 UTC, jonathanheijmans commented on src/delivery-options/main.js
> +// import '@/delivery-options/services/fontAwesome';
commented code

2021-02-03 15:59 UTC, jonathanheijmans commented on src/sandbox/main.js
> +// import '@/sandbox/services/fontAwesome';
commented code

2021-02-11 15:56 UTC, alexmaat approved these changes

2021-02-12 09:51 UTC, mknijnenberg approved these changes

2021-02-12 11:41 UTC, jonathanheijmans approved these changes

2021-03-17 08:38 UTC, merged