My 27240 show delivery date setting
myparcelnl/delivery-options pull request #69
Opened 2021-05-27 08:15 UTC by joerivanveen

Deliveryoptions can pickup allowShowDeliveryDate from myParcelConfig and show / hide the delivery date label / select box accordingly.
This is a per carrier setting with default true.

2021-05-27 08:37 UTC, EdieLemoine requested changes

2021-05-27 08:37 UTC, EdieLemoine commented on src/config/formConfig.js
> +export const SHOW_DELIVERY_DATE = 'showDeliveryDate';
deze hoort hier niet

2021-05-27 08:37 UTC, EdieLemoine commented on src/data/carrierFeatures.js
> +export const FEATURES_SHOW_DELIVERY_DATE = [
hier moet een commentje bij

2021-05-27 08:37 UTC, EdieLemoine commented on src/sandbox/settings/form.js
> +        ...ifAnyCarrierAllows(CONFIG.FEATURE_ALLOW_SHOW_DELIVERY_DATE, {
Die `ifAnyCarrierAllows` hoeft er niet omheen, alle carriers hebben deze optie toch?

2021-05-27 08:46 UTC, joerivanveen commented on src/data/carrierFeatures.js
> +export const FEATURES_SHOW_DELIVERY_DATE = [
sorry dat wist ik... :-(

2021-05-28 12:33 UTC, EdieLemoine approved these changes

2021-06-01 07:54 UTC, RichardPerdaan approved these changes

2021-06-01 08:07 UTC, adem-demir approved these changes

2021-06-11 08:29 UTC, RichardPerdaan approved these changes

2021-06-11 08:31 UTC, EdieLemoine approved these changes

2021-06-11 08:42 UTC, merged