feat: drop off days and related settings per carrier
myparcelnl/delivery-options pull request #74
Opened 2021-06-28 10:50 UTC by joerivanveen

Drop off days, drop off delay and cutoff time are now carrier specific. The carriers that do not support these have the 'show delivery date' switched off, as to not show wrong information.

2021-06-28 11:42 UTC, EdieLemoine requested changes

2021-06-28 11:42 UTC, EdieLemoine commented on src/data/carrierFeatures.js
> +];
Je mist hier weer een nieuwe regel, werkt je ESLint wel?

2021-06-28 11:42 UTC, EdieLemoine commented on src/data/carrierFeatures.js
> + * Permission to show Drop off delay.
die hoofdletters in de namen van de settings zijn niet nodig

2021-06-28 11:42 UTC, EdieLemoine commented on src/sandbox/settings/form.js
> +                options: weekdays.map((day, index) => ({
Deze line is niet gecovered, dat was al zo, maaaaaar, codecov vindt het niet goed. Zou je kunnen kijken of je dit er makkelijk in kunt krijgen? Er is ergens vgm een sandbox components test, misschien kan het daarin ofzo

2021-06-28 11:56 UTC, joerivanveen commented on src/data/carrierFeatures.js
> +];
Oj, ja het werkt wel, hij signaleert t maar doet t niet vanzelf, op mijn windows doet ie t vanzelf, daarom had ik m hier over het hoofd gezien.

2021-07-02 15:18 UTC, EdieLemoine approved these changes

2021-07-02 15:27 UTC, RichardPerdaan approved these changes

2021-07-06 09:58 UTC, merged